export const AP721DatabaseV1Abi = [
  {
    inputs: [
      { internalType: 'uint256', name: '_size', type: 'uint256' },
      { internalType: 'uint256', name: '_start', type: 'uint256' },
      { internalType: 'uint256', name: '_end', type: 'uint256' },
    ],
    name: 'InvalidCodeAtRange',
    type: 'error',
  },
  { inputs: [], name: 'Invalid_Input_Length', type: 'error' },
  { inputs: [], name: 'No_Overwrite_Access', type: 'error' },
  { inputs: [], name: 'No_Remove_Access', type: 'error' },
  { inputs: [], name: 'No_Settings_Access', type: 'error' },
  { inputs: [], name: 'No_Store_Access', type: 'error' },
  { inputs: [], name: 'Target_Not_Initialized', type: 'error' },
  { inputs: [], name: 'Token_Does_Not_Exist', type: 'error' },
  { inputs: [], name: 'WriteError', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'target',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'pointer',
        type: 'address',
      },
    ],
    name: 'DataOverwritten',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'target',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'DataRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'target',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'pointer',
        type: 'address',
      },
    ],
    name: 'DataStored',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'target',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'logic',
        type: 'address',
      },
    ],
    name: 'LogicUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'target',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'renderer',
        type: 'address',
      },
    ],
    name: 'RendererUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'ap721',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'initialOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'logic',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'renderer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'factory',
        type: 'address',
      },
    ],
    name: 'SetupAP721',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'ap721Settings',
    outputs: [
      { internalType: 'uint256', name: 'storageCounter', type: 'uint256' },
      { internalType: 'address', name: 'logic', type: 'address' },
      { internalType: 'uint8', name: 'initialized', type: 'uint8' },
      { internalType: 'address', name: 'renderer', type: 'address' },
      {
        components: [
          { internalType: 'address', name: 'fundsRecipient', type: 'address' },
          { internalType: 'uint16', name: 'royaltyBPS', type: 'uint16' },
          { internalType: 'bool', name: 'transferable', type: 'bool' },
        ],
        internalType: 'struct IAP721Database.AP721Config',
        name: 'ap721Config',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'canEditSettings',
    outputs: [{ internalType: 'bool', name: 'access', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'canOverwrite',
    outputs: [{ internalType: 'bool', name: 'access', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'canRemove',
    outputs: [{ internalType: 'bool', name: 'access', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
    ],
    name: 'canStore',
    outputs: [{ internalType: 'bool', name: 'access', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'contractURI',
    outputs: [{ internalType: 'string', name: 'uri', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'getSettings',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'storageCounter', type: 'uint256' },
          { internalType: 'address', name: 'logic', type: 'address' },
          { internalType: 'uint8', name: 'initialized', type: 'uint8' },
          { internalType: 'address', name: 'renderer', type: 'address' },
          {
            components: [
              {
                internalType: 'address',
                name: 'fundsRecipient',
                type: 'address',
              },
              { internalType: 'uint16', name: 'royaltyBPS', type: 'uint16' },
              { internalType: 'bool', name: 'transferable', type: 'bool' },
            ],
            internalType: 'struct IAP721Database.AP721Config',
            name: 'ap721Config',
            type: 'tuple',
          },
        ],
        internalType: 'struct IAP721Database.Settings',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'getTransferable',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'isInitialized',
    outputs: [{ internalType: 'bool', name: 'initialized', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
      { internalType: 'bytes[]', name: 'data', type: 'bytes[]' },
    ],
    name: 'overwrite',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
    name: 'readAllData',
    outputs: [{ internalType: 'bytes[]', name: 'allData', type: 'bytes[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'readData',
    outputs: [{ internalType: 'bytes', name: 'data', type: 'bytes' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
    ],
    name: 'remove',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'logic', type: 'address' },
      { internalType: 'bytes', name: 'logicInit', type: 'bytes' },
    ],
    name: 'setLogic',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'address', name: 'renderer', type: 'address' },
      { internalType: 'bytes', name: 'rendererInit', type: 'bytes' },
    ],
    name: 'setRenderer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'initialOwner', type: 'address' },
      { internalType: 'bytes', name: 'databaseInit', type: 'bytes' },
      { internalType: 'address', name: 'factory', type: 'address' },
      { internalType: 'bytes', name: 'factoryInit', type: 'bytes' },
    ],
    name: 'setupAP721',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'store',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'tokenData',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: 'uri', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
