// SPDX-License-Identifier: MIT
pragma solidity ^0.8.16;

import {IERC1155PressTokenLogic} from "./IERC1155PressTokenLogic.sol";
import {IERC1155TokenRenderer} from "./IERC1155TokenRenderer.sol";
import {IERC1155PressContractLogic} from "./IERC1155PressContractLogic.sol";


interface IERC1155Press {
    // ||||||||||||||||||||||||||||||||
    // ||| TYPES ||||||||||||||||||||||
    // ||||||||||||||||||||||||||||||||

    // stores token level logic + renderer + funds + transferability related information
    struct Configuration {
        address payable fundsRecipient;
        IERC1155PressTokenLogic logic;
        IERC1155TokenRenderer renderer;
        address payable primarySaleFeeRecipient;
        bool soulbound;
        uint16 royaltyBPS;
        uint16 primarySaleFeeBPS;        
    }

    // ||||||||||||||||||||||||||||||||
    // ||| ERRORS |||||||||||||||||||||
    // ||||||||||||||||||||||||||||||||

    // Access errors
    /// @notice msg.sender does not have mint new access for given Press
    error No_MintNew_Access();    
    /// @notice msg.sender does not have mint existing access for given Press
    error No_MintExisting_Access();
    /// @notice msg.sender does not have config access for given Press + tokenId
    error No_Config_Access();     
    /// @notice msg.sender does not have withdraw access for given Press
    error No_Withdraw_Access();    
    /// @notice cannot withdraw balance from a tokenId with no associated funds  
    error No_Withdrawable_Balance(uint256 tokenId);     
    /// @notice msg.sender does not have burn access for given Press + tokenId
    error No_Burn_Access();    
    /// @notice msg.sender does not have upgrade access for given Press
    error No_Upgrade_Access();     
    /// @notice msg.sender does not have owernship transfer access for given Press
    error No_Transfer_Access();       

    // Constraint/invalid/failure errors
    /// @notice invalid input
    error Invalid_Input();
    /// @notice If minted total supply would exceed max supply
    error Exceeds_MaxSupply();    
    /// @notice invalid contract inputs due to parameter.length mismatches
    error Input_Length_Mismatch();
    /// @notice token doesnt exist error
    error Token_Doesnt_Exist(uint256 tokenId);    
    /// @notice incorrect msg.value for transaction
    error Incorrect_Msg_Value();    
    /// @notice cant set address
    error Cannot_Set_Zero_Address();
    /// @notice cannot set royalty or finders fee bps this high
    error Setup_PercentageTooHigh(uint16 maxBPS);    
    /// @notice Cannot withdraw funds due to ETH send failure
    error Withdraw_FundsSendFailure();    
    /// @notice error setting config varibles
    error Set_Config_Fail(); 

    // ||||||||||||||||||||||||||||||||
    // ||| EVENTS |||||||||||||||||||||
    // ||||||||||||||||||||||||||||||||    

    /// @notice Event emitted upon ERC1155Press initialization
    /// @param sender msg.sender calling initialization function
    /// @param owner initial owner of contract
    /// @param contractLogic logic contract set 
    event ERC1155PressInitialized(
        address indexed sender,        
        address indexed owner,
        IERC1155PressContractLogic indexed contractLogic
    );          

    /// @notice Event emitted when minting a new token
    /// @param tokenId tokenId being minted
    /// @param sender msg.sender calling mintNew function
    /// @param recipient recipient of tokens
    /// @param quantity quantity of tokens received by recipient 
    event NewTokenMinted(
        uint256 indexed tokenId,        
        address indexed sender,
        address indexed recipient,
        uint256 quantity
    );    

    /// @notice Event emitted when minting an existing token
    /// @param tokenId tokenId being minted
    /// @param sender msg.sender calling mintExisting function
    /// @param recipient recipient of tokens
    /// @param quantity quantity of tokens received by recipient 
    event ExistingTokenMinted(
        uint256 indexed tokenId,        
        address indexed sender,
        address indexed recipient,
        uint256 quantity
    );

    /// @notice Event emitted when adding to a tokenId's funds tracking
    /// @param tokenId tokenId being minted
    /// @param sender msg.sender passing value
    /// @param amount value being added to tokenId's funds tracking
    event TokenFundsIncreased(
        uint256 indexed tokenId,        
        address indexed sender,
        uint256 amount
    );    

    /// @notice Event emitted when the funds generated by a given tokenId are withdrawn from the minting contract
    /// @param tokenId tokenId to withdraw generated funds from
    /// @param sender address that issued the withdraw
    /// @param fundsRecipient address that the funds were withdrawn to
    /// @param fundsAmount amount that was withdrawn
    /// @param feeRecipient user getting withdraw fee (if any)
    /// @param feeAmount amount of the fee getting sent (if any)
    event TokenFundsWithdrawn(
        uint256 indexed tokenId,        
        address indexed sender,
        address indexed fundsRecipient,        
        uint256 fundsAmount,
        address feeRecipient,
        uint256 feeAmount
    );    

    /// @notice Event emitted when config is updated post initialization
    /// @param tokenId tokenId config being updated
    /// @param sender address that sent update txn
    /// @param logic logic contract address
    /// @param renderer renderer contract address
    /// @param fundsRecipient fundsRecipient
    /// @param royaltyBPS royaltyBPS
    /// @param soulbound soulbound bool
    event UpdatedConfig(
        uint256 indexed tokenId,
        address indexed sender,        
        IERC1155PressTokenLogic logic,
        IERC1155TokenRenderer renderer,
        address fundsRecipient,
        uint16 royaltyBPS,
        bool soulbound
    );    

    // ||||||||||||||||||||||||||||||||
    // ||| FUNCTIONS ||||||||||||||||||
    // ||||||||||||||||||||||||||||||||

    /// @notice Public owner setting that can be set by the contract admin
    function owner() external view returns (address);

    /// @notice URI getter for a given tokenId
    function uri(uint256 tokenId) external view returns (string memory);

    /// @notice Amount of existing (minted & not burned) tokens with a given tokenId
    function totalSupply(uint256 tokenId) external view returns (uint256);

    /// @notice getter for internal _numMinted counter which keeps track of quantity minted per tokenId per wallet address
    function numMinted(uint256 tokenId, address account) external view returns (uint256);    

    /// @notice Getter for last minted tokenId
    function tokenCount() external view returns (uint256);

    /// @notice Getter for contract level logic contract
    function getContractLogic() external view returns (IERC1155PressContractLogic); 

    /// @notice Getter for logic contract stored in configInfo for a given tokenId
    function getTokenLogic(uint256 tokenId) external view returns (IERC1155PressTokenLogic); 

    /// @notice Getter for renderer contract stored in configInfo for a given tokenId
    function getRenderer(uint256 tokenId) external view returns (IERC1155TokenRenderer); 

    /// @notice Getter for fundsRecipent address stored in configInfo for a given tokenId
    function getFundsRecipient(uint256 tokenId) external view returns (address payable); 

    /// @notice Getter for logic contract stored in configInfo for a given tokenId
    function getRoyaltyBPS(uint256 tokenId) external view returns (uint16);

    /// @notice Getter for `primarySaleFeeRecipient` address stored in configInfo for a given tokenId
    function getPrimarySaleFeeRecipient(uint256 tokenId) external view returns (address payable);

    /// @notice Getter for `primarySaleFeeBPS` stored in configInfo for a given tokenId
    function getPrimarySaleFeeBPS(uint256 tokenId) external view returns (uint16);

    /// @notice returns true if token type `id` is soulbound
    function isSoulbound(uint256 id) external view returns (bool);

    /// @notice Config level details
    /// @return Configuration (defined in IERC1155Press) 
    function getConfigDetails(uint256 tokenId) external view returns (Configuration memory);

    /// @dev Get royalty information for token
    /// @param _salePrice Sale price for the token
    function royaltyInfo(uint256 _tokenId, uint256 _salePrice) external view returns (address receiver, uint256 royaltyAmount);

    /// @notice ERC165 supports interface
    /// @param interfaceId interface id to check if supported
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}
